# Generated by Django 4.1.7 on 2023-03-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Images',
            field=models.FileField(upload_to='media/'),
        ),
    ]
